syntax = "proto3";
package cros.factory.hwid.service.appengine.proto.ingestion_pb2;

message IngestHwidDbRequest {
  repeated string limit_models = 1;
  bool force_push = 2;
  repeated string limit_boards = 3;
  bool skip_model_check = 4;
}

message IngestHwidDbResponse {
  string msg = 1;
  map<string, string> payload_hash = 2;
  map<string, string> hwid_selection_payload_hash = 3;
  map<string, string> rmad_feature_enabled_devices_payload_hash = 4;
}

message IngestDevicesVariantsRequest {
}

message IngestDevicesVariantsResponse {
}

message SyncNameMappingRequest {
}

message SyncNameMappingResponse {
}

message IngestVpgTargetsRequest {
}

message IngestVpgTargetsResponse {
}

service HwidIngestion {
  rpc IngestHwidDb(IngestHwidDbRequest) returns (IngestHwidDbResponse);

  rpc IngestDevicesVariants(IngestDevicesVariantsRequest)
      returns (IngestDevicesVariantsResponse);

  rpc SyncNameMapping(SyncNameMappingRequest) returns (SyncNameMappingResponse);

  rpc IngestVpgTargets(IngestVpgTargetsRequest)
      returns (IngestVpgTargetsResponse);
}
