#!/usr/bin/env python3
# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""A script for installing an apk as a priv-app.

In this script, we have two users, 0 (system user) and 10 (owner). To learn more
about the difference, check
https://source.android.com/docs/automotive/users_accounts/multi_user

Dependencies:
1. adb
2. aapt2
3. apkanalyzer
"""

import argparse
import dataclasses
import enum
import logging
import pathlib
import re
import shlex
import subprocess
import sys
import time
from typing import List, Optional, Sequence, Union
import xml.etree.ElementTree as ET


_PACKAGE_NAME_PATTERN = re.compile(r"package: name='([^']*)'")
_PERMISSION_PATTERN = re.compile(r"uses-permission: name='([^']*)'", re.M)
_PRIVILEGED_PATTERN = re.compile(r'^.*\bprivateFlags=.*\bPRIVILEGED\b.*$', re.M)


def Run(
    args: Union[str, Sequence[str]],
    *,
    shell=False,
    cwd: Optional[str] = None,
    check=True,
    encoding: Optional[str] = 'utf-8',
    log=True,
    **kwargs,
):
  """A wrapper of `subprocess.run`.

  Differences:
  1. All parameters except args are keyword-only.
  2. `check` default to True
  3. `encoding` default to 'utf-8'
  4. Log running command into logging.info by default.
  """
  args_to_log: str
  if shell:
    if not isinstance(args, str):
      raise TypeError('Command must be a string when shell is specified.')
    args_to_log = args
  else:
    if isinstance(args, str):
      raise TypeError('Command must be a sequence (list/tuple) of string.')
    args_to_log = ' '.join(map(shlex.quote, args))
  if log:
    message = f'Running command: "{args_to_log}"'
    if cwd is not None:
      message += f' in {cwd}'
    logging.info(message)
  return subprocess.run(args, shell=shell, cwd=cwd, check=check,
                        encoding=encoding, **kwargs)


class AndroidPartition(enum.Enum):
  system = pathlib.Path('system')
  system_ext = pathlib.Path('system_ext')
  vendor = pathlib.Path('vendor')
  product = pathlib.Path('product')

  def __str__(self) -> str:
    return self.name


@dataclasses.dataclass
class InstallAsPrivAppArgs:
  apk_path: pathlib.Path
  dir_app_name: str
  dpc_enabled: bool
  dpc_receiver_name: str
  skip_factory_settings: bool
  partition: AndroidPartition
  target: Optional[str] = None
  package_name: str = ''
  permission_path: pathlib.Path = pathlib.Path()
  uninstall_previous: bool = False

  @property
  def dpc_admin(self):
    return f'{self.package_name}/{self.dpc_receiver_name}'

  @property
  def adb(self):
    result = ['adb']
    if self.target:
      result.extend(['-s', self.target])
    return result


def MakeParser():
  parser = argparse.ArgumentParser(
      description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
  parser.add_argument('apk_path', metavar='APK_PATH', type=pathlib.Path,
                      help='Path to the apk.')
  parser.add_argument('--target', type=str,
                      help='Use as HOST in adb connection.')
  parser.add_argument('--dir_app_name', type=str, default='Factory',
                      help='The apk name on the device.')
  parser.add_argument('--uninstall_previous', action='store_true',
                      help='Uninstall the app before deployment.')
  parser.add_argument('--dpc_enabled', action='store_true',
                      help='If set, makes the install app the device owner.')
  parser.add_argument('--dpc_receiver_name', type=str, default='',
                      help='The receiver of the device owner app.')
  parser.add_argument(
      '--skip_factory_settings', action='store_true',
      help=('If set, skip factory settings. Factory settings include stay on '
            'while plugged in and other configurations. Check '
            'SetFactorySettings for detail.'))
  parser.add_argument('--partition', type=AndroidPartition.__getitem__,
                      default=AndroidPartition.system,
                      choices=AndroidPartition.__members__.values(),
                      help='The target partition to install.')
  return parser


def ParsePackageName(apk_info: str):
  match = _PACKAGE_NAME_PATTERN.match(apk_info)
  if match is None:
    logging.info('No package name in apk_info')
    sys.exit(1)
  return match.group(1)


def ParseDPCReceiverName(args: InstallAsPrivAppArgs):
  """Parses DPC receiver name from AndroidManifest.xml generated by apkanalyzer.

  Returns:
    The receiver name or empty str if not found.
  Raises:
    ValueError: If multiple receivers are found.
  """
  result = Run([
      'apkanalyzer',
      'manifest',
      'print',
      str(args.apk_path),
  ], stdout=subprocess.PIPE)
  dpc_receivers = []
  root = ET.fromstring(result.stdout)
  for application in root.iter('application'):
    for receiver in application.iter('receiver'):
      is_dpc_receiver = False
      name = None
      for (key, value) in receiver.attrib.items():
        if (key == r'{http://schemas.android.com/apk/res/android}permission' and
            value == 'android.permission.BIND_DEVICE_ADMIN'):
          is_dpc_receiver = True
        if key == r'{http://schemas.android.com/apk/res/android}name':
          name = value
      if is_dpc_receiver and name:
        dpc_receivers.append(name)

  if len(dpc_receivers) > 1:
    raise ValueError(f'Set --dpc_receiver_name to one of {dpc_receivers!r}')
  return '' if not dpc_receivers else dpc_receivers[0]


def GeneratePermissionFile(args: InstallAsPrivAppArgs, apk_info: str):
  with args.permission_path.open('w', encoding='utf-8') as f:
    f.write('<permissions>\n')
    f.write(f'  <privapp-permissions package="{args.package_name}">\n')
    for match in _PERMISSION_PATTERN.finditer(apk_info):
      f.write(f"    <permission name='{match.group(1)}' />\n")
    f.write('  </privapp-permissions>\n')
    f.write('</permissions>\n')


def UnInstallPreviousForUser(args: InstallAsPrivAppArgs, userId: int):
  result = Run(
      args.adb + ['shell', 'pm', 'list', 'package', '--user',
                  str(userId)], stdout=subprocess.PIPE)
  pattern = re.compile(rf'^package:{args.package_name}\b.*$', re.M)
  match = pattern.findall(result.stdout)
  logging.info('UnInstallPreviousForUser userId=%s match=%s', userId, match)
  if match:
    Run(args.adb + ['uninstall', '--user', str(userId), args.package_name])


def SwitchUser(args: InstallAsPrivAppArgs, user: int):
  """Switch user to expected state.

  After reboot/first boot, the running foreground user is usually user 0 and the
  system UI will wait for a user to login.

  We want to automatically login and let the app run by user 10.
  """
  Run(args.adb + ['shell', 'am', 'switch-user', str(user)])


def DeprovisionDPC(args: InstallAsPrivAppArgs):
  """Deprovision DPC before installation.

  With dpc enabled, we cannot uninstall/re-install the device owner app without
  deprovision first.

  Do this even if args.dpc_enabled is False since the app might be provisioned
  by a previous command with args.dpc_enabled==True.
  """
  if not args.dpc_receiver_name:
    return
  for user in (10, 0):
    result = Run(
        args.adb + [
            'shell', 'dpm', 'remove-active-admin', '--user',
            str(user), args.dpc_admin
        ], check=False)
    if result.returncode == 0:
      time.sleep(3.0)


def UnInstallPrevious(args: InstallAsPrivAppArgs):
  """Uninstall previous package."""
  if not args.uninstall_previous:
    return
  for user in (10, 0):
    UnInstallPreviousForUser(args, user)


def WaitForSystem(args: InstallAsPrivAppArgs):
  Run(args.adb + ['wait-for-device'])
  # Wait until package manager is up so we can launch activity.
  while True:
    result = Run(args.adb + ['shell', 'dumpsys', '-l'], stdout=subprocess.PIPE)
    if 'package' in result.stdout:
      break
    time.sleep(1.0)
  Run(args.adb + ['root'])


def InstallApk(args: InstallAsPrivAppArgs):
  """Install an apk.

  1. -g grants runtime permissions
  2. -t allows test-only packages
     Check
     https://developer.android.com/guide/topics/manifest/application-element#testOnly
     for doc of test-only packages. Additionally, We cannot remove a device
     owner with `adb shell dpm remove-active-admin` unless the device owner is a
     test-only package.
  """  # pylint: disable=line-too-long
  Run(args.adb + ['install', '-g', '-t', str(args.apk_path)])


def Remount(args: InstallAsPrivAppArgs):
  Run(args.adb + ['root'])
  result = Run(args.adb + ['remount', '-R'], check=False)
  if result.returncode == 255:
    logging.info('return code is 255. Wait for reboot completed.')
    WaitForSystem(args)
    Run(args.adb + ['remount'])
  elif result.returncode == 0:
    logging.info('return code is 0. The device is already remounted.')
  else:
    logging.info('return code is %s.', result.returncode)
    sys.exit(1)


def Install(args: InstallAsPrivAppArgs):
  on_device_dir_path = args.partition.value / 'priv-app' / args.dir_app_name
  Run(args.adb + ['shell', 'mkdir', '-p', str(on_device_dir_path)])
  Run(args.adb + ['shell', 'chmod', '755', str(on_device_dir_path)])

  on_device_apk_path = on_device_dir_path / f'{args.dir_app_name}.apk'
  Run(args.adb + ['push', str(args.apk_path), str(on_device_apk_path)])
  Run(args.adb + ['shell', 'chmod', '644', str(on_device_apk_path)])

  on_device_permission_path = args.partition.value / pathlib.Path(
      'etc', 'permissions', f'privapp-permissions-{args.dir_app_name}.xml')
  Run(args.adb +
      ['push',
       str(args.permission_path),
       str(on_device_permission_path)])
  Run(args.adb + ['shell', 'chmod', '644', str(on_device_permission_path)])

  InstallApk(args)

  result = Run(args.adb + ['shell', 'dumpsys', 'package', args.package_name],
               stdout=subprocess.PIPE)
  match = _PRIVILEGED_PATTERN.findall(result.stdout)
  for line in match:
    logging.info('%s', line)
  if not match:
    logging.info('App is not privileged and requires a reboot to enable '
                 'privileged.')
    Run(args.adb + ['reboot'])
    WaitForSystem(args)
    # Previous -g will be invalidated after reboot if the package was not
    # privileged.
    InstallApk(args)
  else:
    logging.info('App is already privileged.')


def SetFactorySettings(args: InstallAsPrivAppArgs):
  if args.skip_factory_settings:
    return
  Run(args.adb +
      ['shell', 'settings', 'put', 'global', 'stay_on_while_plugged_in', '3'])


def LaunchApp(args: InstallAsPrivAppArgs):
  if args.dpc_enabled:
    Run(args.adb +
        ['shell', 'dpm', 'set-device-owner', '--user', '0', args.dpc_admin])
  else:
    Run(args.adb + ['shell', 'am', 'start', args.package_name])


def DoMain(argv: List[str]):
  parser = MakeParser()
  args = InstallAsPrivAppArgs(**parser.parse_args(argv).__dict__)
  result = Run(['aapt2', 'dump', 'badging',
                str(args.apk_path)], stdout=subprocess.PIPE)
  apk_info = result.stdout
  args.package_name = ParsePackageName(apk_info)
  logging.info('package_name="%s"', args.package_name)

  args.dpc_receiver_name = args.dpc_receiver_name or ParseDPCReceiverName(args)
  logging.info('dpc_receiver_name="%s"', args.dpc_receiver_name)

  if args.dpc_enabled and not args.dpc_receiver_name:
    sys.exit('Cannot enable dpc. No receiver is defined.')

  args.permission_path = (
      args.apk_path.parent / f'privapp-permissions-{args.dir_app_name}.xml')
  logging.info('permission_path="%s"', args.permission_path)
  GeneratePermissionFile(args, apk_info)
  if args.target is not None:
    Run(['adb', 'connect', args.target])
  Remount(args)  # DUT will reboot if it's not already remounted.
  DeprovisionDPC(args)
  UnInstallPrevious(args)
  Install(args)  # DUT will reboot if the app is not priv-app before this.
  SetFactorySettings(args)
  SwitchUser(args, 10)
  LaunchApp(args)


if __name__ == '__main__':
  logging.basicConfig(level=logging.INFO)
  DoMain(sys.argv[1:])
