# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""Defines classes building a probe config for Runtime Probe."""

import typing

from cros.factory.probe.runtime_probe import matchers
from cros.factory.probe.runtime_probe import probe_types
from cros.factory.utils import json_utils


class ProbeConfigBuilder:
  """Builds a probe config.

  A probe config is a json with the following format:

  {"CATEGORY_NAME": {
    "COMPONENT_NAME": {
      "eval": {"PROBE_FUNCTION_NAME": {PROBE_FUNCTION_ARGUMENT...}},
      "matcher": {MATCHER_STATEMENT...},
      "expect": {EXPECT_STATEMENT...}
    }...
  }...}

  Note that the "expect" is the legacy syntax to match the component, while
  "matcher" is the newer one to replace it. These two cannot exist in a
  component at the same time.

  By design, all the components in a category should be the same type, that is,
  they will have the same fields in the probe results. However, this is
  currently not enforced so category is only for grouping components.

  TODO(chungsheng): Migrate "expect" syntax to "matcher".
  TODO(chungsheng): Evaluate how to enforce the category checking, e.g. by
    using protobuf and define the fields output by each probe function.

  Args:
    base_json: A json string containing config generated by other builder. This
               is for migration from other legacy builders.
  """

  def __init__(self, base_json: str = '{}'):
    self._result = json_utils.LoadStr(base_json)

  def AddComponent(self, category_name: str, component_name: str,
                   probe_function: probe_types.ProbeFunction,
                   matcher: typing.Optional[matchers.IMatcher] = None):
    if category_name not in self._result:
      self._result[category_name] = {}
    if component_name in self._result[category_name]:
      raise ValueError(f'Component {component_name} has already '
                       f'been added to category {category_name}')
    probe_statement = {
        'eval': {
            probe_function.name: probe_function.args
        },
    }
    if matcher:
      probe_statement['matcher'] = dict(
          matcher.GenerateProbeConfigMatcherStatement())

    self._result[category_name][component_name] = probe_statement

  def Build(self) -> str:
    """Builds the probe config and returns the json string.
    """
    return json_utils.DumpStr(self._result, pretty=True)
