# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

[mypy]
mypy_path = $MYPY_CONFIG_FILE_DIR/../../py_pkg/
exclude = (?x)(
    ; Paths that shouldn't be checked.
    /\S+\.venv/
    | ^py_pkg/
    | ^build/
    | ^py/experimental/
    | .*_pb2.py$
    | ^py/dome/backend/migrations/
    ; Paths that is not ready to be checked.
    | ^doc/
    | ^go/src/overlord/
    | ^py/bundle_creator/
    | ^py/cli/test_list_insight.py
    | ^py/device/chromeos/display.py
    | ^py/external/chromeos_cli/flashrom.py
    | ^py/hwid/service/appengine/app.py
    | ^py/hwid/service/appengine/data/converter/converter.py
    | ^py/hwid/service/appengine/feature_matching.py
    | ^py/hwid/service/appengine/feature_matching_test.py
    | ^py/hwid/v2/yaml_datastore.py
    | ^py/instalog/lock_utils.py
    | ^py/instalog/plugins/output_socket.py
    | ^py/probe_info_service/app_engine/probe_tools/resources/runtime_probe_wrapper.py
    | ^py/test/event.py
    | ^py/test/pytests/keyboard_unittest.py
    | ^py/test/rf/e5071c_mock.py
    | ^py/test/session_unittest.py
    | ^py/test/utils/drm_utils.py
    | ^py/test_list_editor/backend/models/test_list_unittest.py
    | ^py/tools/test_list_insight.py
    | ^py/umpire/server/service/umpire_service.py
    | ^py/umpire/server/service/umpire_service_unittest.py
    | ^py/utils/cros_board_utils.py
  )

warn_unused_configs = True
check_untyped_defs = True

; Remove following configs after we fix most errors.
; Ignore all errors caused by imported files.
follow_imports = silent
allow_untyped_globals = True

[mypy-google.api_core.*]
ignore_missing_imports = True
follow_imports = skip

[mypy-google.cloud.*]
ignore_missing_imports = True
follow_imports = skip

[mypy-google.auth.*]
ignore_missing_imports = True
follow_imports = skip

[mypy-google.oauth2.*]
ignore_missing_imports = True
follow_imports = skip

[mypy-jsonrpclib]
ignore_missing_imports = True

[mypy-spyne.*]
ignore_missing_imports = True

[mypy-twisted.*]
ignore_missing_imports = True

[mypy-txjsonrpc.*]
ignore_missing_imports = True

[mypy-zeep.*]
ignore_missing_imports = True
