syntax = "proto3";

package com.google.android.factory.factory.proto.umpire;

import "google/protobuf/empty.proto";

message UpdateFactoryAppRequest {
  string target = 1;
}

message UpdateFactoryAppResponse {
  bool success = 1;
  string messages = 2;
}

enum Component {
  COMPONENT_NONE = 0;
  COMPONENT_TOOLKIT = 1;
}

message GetUpdateVersionRequest {
  Component component = 1;
}

message GetUpdateVersionResponse {
  string version = 1;
}

enum PayloadType {
  PAYLOAD_TYPE_UNKNOWN = 0;
  PAYLOAD_TYPE_APK = 1;
  PAYLOAD_TYPE_OTA = 2;
}

message DownloadPayloadRequest {
  string target = 1;
  string path = 2;
  PayloadType payload_type = 3;
}

message DownloadPayloadResponse {
  bool success = 1;
  string messages = 2;
}

message DownloadFactoryDrivesRequest {
  string target = 1;
  string dest_path = 2;
  string source_namespace = 3;
  string source_file = 4;
}

message DownloadFactoryDrivesResponse {
  bool success = 1;
  string messages = 2;
}

enum TestPhase {
  TEST_PHASE_UNKNOWN = 0;
  TEST_PHASE_PROTO = 1;
  TEST_PHASE_EVT = 2;
  TEST_PHASE_DVT = 3;
  TEST_PHASE_PVT = 4;
  TEST_PHASE_MP = 5;
}

message DeviceMetadata {
  string serial_number = 1;
  TestPhase test_phase = 2;
}

message UploadFileRequest {
  oneof data {
    DeviceMetadata device_metadata = 1;
    bytes chunk = 2;
  }
}

message GetOtaPackageRequest {
  string target = 1;
  string path = 2;
}

message GetOtaPackageResponse {
  bool success = 1;
  string messages = 2;
}

message SyncDeviceTimeRequest {
  string target = 1;
}

message SyncDeviceTimeResponse {
  bool success = 1;
  string messages = 2;
}

service UmpireDUTCommands {
  /* Update the factory app on target device with adb. */
  rpc UpdateFactoryApp(UpdateFactoryAppRequest)
      returns (UpdateFactoryAppResponse) {}

  /* Return the version of a component.
   *
   * In xmlrpc, DUT gets the cros_payload JSON file by GetCROSPayloadURL and
   * parses the bundle information from it. Check Updater.GetUpdateInfo. In
   * grpc, this API returns the version directly.
   */
  rpc GetUpdateVersion(GetUpdateVersionRequest)
      returns (GetUpdateVersionResponse) {}

  /* Get the factory app apk to the target device with adb. */
  rpc DownloadPayload(DownloadPayloadRequest)
      returns (DownloadPayloadResponse) {}

  /* Get the FactoryDrives file to the target device with adb. */
  rpc DownloadFactoryDrives(DownloadFactoryDrivesRequest)
      returns (DownloadFactoryDrivesResponse) {}

  /* Uploads factory report to the factory server.
   *
   * Compared to the XLM-RPC report upload method, this one compresses a report
   * (hint: a report is a single file) to zst at the factory server side, and
   * supports streaming upload.
   */
  rpc UploadReport(stream UploadFileRequest) returns (.google.protobuf.Empty) {}

  /* Get the user image OTA package to the target device with adb. */
  rpc GetOtaPackage(GetOtaPackageRequest) returns (GetOtaPackageResponse) {}

  /* Synchronizes the target device's time zone to the Umpire server's time
   * zone.
   */
  rpc SyncDeviceTime(SyncDeviceTimeRequest) returns (SyncDeviceTimeResponse) {}
}
