syntax = "proto3";

package com.google.android.factory.factory.proto.umpire;

message UpdateFactoryAppRequest {
  string target = 1;
  bool dpc = 2;
}

message UpdateFactoryAppResponse {
  bool success = 1;
  string messages = 2;
}

enum Component {
  COMPONENT_NONE = 0;
  COMPONENT_TOOLKIT = 1;
}

message GetUpdateVersionRequest {
  Component component = 1;
}

message GetUpdateVersionResponse {
  string version = 1;
}

/* Metadata for uploading factory report. */
message ReportMetadata {
  /* The serial number of the DUT. */
  string serial_number = 1;
  /* The testing stage; e.g. SMT, FAT, RUNIN, FFT, or GRT. */
  string stage = 2;
}

message UploadReportRequest {
  oneof data {
    ReportMetadata metadata = 1;
    bytes chunk = 2;
  }
}

message UploadReportResponse {
  bool success = 1;
}

message GetOtaPackageRequest {
  string target = 1;
  string path = 2;
}

message GetOtaPackageResponse {
  bool success = 1;
  string messages = 2;
}

service UmpireDUTCommands {
  /* Update the factory app on target device with adb. */
  rpc UpdateFactoryApp(UpdateFactoryAppRequest)
      returns (UpdateFactoryAppResponse) {}

  /* Return the version of a component.
   *
   * In xmlrpc, DUT gets the cros_payload JSON file by GetCROSPayloadURL and
   * parses the bundle information from it. Check Updater.GetUpdateInfo. In
   * grpc, this API returns the version directly.
   */
  rpc GetUpdateVersion(GetUpdateVersionRequest)
      returns (GetUpdateVersionResponse) {}

  /* Uploads factory report to the factory server.
   *
   * Compared to the xmlrpc uploading report method, this method compresses the
   * report as zst at the factory server side and supports streaming upload. The
   * report is a single file.
   */
  rpc UploadReport(stream UploadReportRequest) returns (UploadReportResponse) {}

  /* Get the user image OTA package to the target device with adb. */
  rpc GetOtaPackage(GetOtaPackageRequest) returns (GetOtaPackageResponse) {}
}
