# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Generated by Django 4.2.17 on 2025-02-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('backend', '0019_domeconfig_version_check_enabled'),
  ]

  operations = [
      migrations.AddField(
          model_name='project',
          name='is_android',
          field=models.BooleanField(default=False),
      ),
  ]
