# Copyright 2026 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Generated by Django 4.2.17 on 2026-03-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ('backend', '0020_project_is_android'),
  ]

  operations = [
    migrations.AddField(
      model_name='domeconfig',
      name='broadcast_ping_enabled',
      field=models.BooleanField(default=False),
    ),
  ]
