# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""A proxy servicer for the underlying shopfloor.

This is the gRPC implementation of
src/platform/factory/py/umpire/server/rpc_dut.py.

It implements the abstract methods generated by python gRPC class
shop_floor_pb2_grpc.ShopFloorServicer.

The topology:

DUT <== gRPC ==> This servicer <== webservice_utils ==> shopfloor

We run this servicer in the factory server so we don't need to support SOAP or
xmlrpc in DUT.

The methods are not yet implemented.
"""

import logging

from cros.factory.umpire.server.proto import shop_floor_pb2
from cros.factory.umpire.server.proto import shop_floor_pb2_grpc


class ShopFloorServicer(shop_floor_pb2_grpc.ShopFloorServicer):

  def GetVersion(self, request, context):
    del request
    del context
    logging.info('GetVersion')
    return shop_floor_pb2.GetVersionResponse(version="1.0")
