# Copyright 2023 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""Classes for payload generation and synchronization from HWID DB."""

import abc
import collections
import hashlib
import logging
import os
import os.path
import re
import textwrap
from typing import Collection, Mapping, NamedTuple, Optional, Sequence

from cros.factory.hwid.service.appengine.data import cl_upload_config
from cros.factory.hwid.service.appengine.data import config_data as config_data_module
from cros.factory.hwid.service.appengine.data import decoder_data as decoder_data_module
from cros.factory.hwid.service.appengine.data import vpg_targets_data
from cros.factory.hwid.service.appengine import feature_matching
from cros.factory.hwid.service.appengine import git_util
from cros.factory.hwid.service.appengine import hwid_action_manager as hwid_action_manager_module
from cros.factory.hwid.service.appengine import hwid_repo
from cros.factory.hwid.service.appengine import verification_payload_generator as vpg_module
from cros.factory.hwid.service.appengine import verification_payload_generator_config as vpg_config_module
from cros.factory.probe_info_service.app_engine import protorpc_utils
from cros.factory.utils import json_utils


class _Payload(NamedTuple):
  """Holds data generated by PayloadManager._GeneratePayloads().

  Attributes:
    contents: The generated payload contents in form of a dictionary mapping
      file names to content.
    hash_value: The hash value of contents.
    metadata: Additional payload metadata.
  """
  contents: Mapping[str, str]
  hash_value: str
  # TODO(kevinptt): Make metadata typeable.
  metadata: dict


class UpdatedResult(NamedTuple):
  """A holder of result."""
  payload_hash: str
  change_id: str


def _JSONHash(data) -> str:
  """Calculates the SHA1 hash value of given data."""
  data_json = json_utils.DumpStr(data, sort_keys=True)
  data_hash = hashlib.sha1(data_json.encode('utf-8')).hexdigest()
  return data_hash


class PayloadGenerationException(protorpc_utils.ProtoRPCException):
  """Exception to group similar exceptions for error reporting."""

  def __init__(self, msg):
    super().__init__(protorpc_utils.RPCCanonicalErrorCode.INTERNAL, detail=msg)


class PayloadManager(abc.ABC):
  """A base class managing payloads generated from HWID DB."""

  def __init__(
      self, cl_upload_manager: cl_upload_config.PayloadCLUploadManager,
      hwid_action_manager: hwid_action_manager_module.HWIDActionManager,
      config_data: config_data_module.Config):

    self._logger = logging.getLogger(self.__class__.__name__)
    self._cl_upload_manager = cl_upload_manager
    self._hwid_action_manager = hwid_action_manager
    self._config_data = config_data
    self._gerrit_credentials = None
    self._auth_cookie = None

  @property
  def _author(self) -> str:
    service_account_name = self._gerrit_credentials[0]  # type: ignore #TODO(b/338318729) Fixit! # pylint: disable=line-too-long
    return f'chromeoshwid <{service_account_name}>'

  def _RefreshCredential(self):
    self._gerrit_credentials = git_util.GetGerritCredentials()
    self._auth_cookie = git_util.GetGerritAuthCookie(self._gerrit_credentials)

  @abc.abstractmethod
  def _GetSupportedModels(
      self, limit_models: Collection[str],
      live_hwid_repo: hwid_repo.HWIDRepo) -> Mapping[str, Collection[str]]:
    """Returns models supported by the generator.

    Args:
      limit_models: See Update().
      live_hwid_repo: See Update().

    Returns:
      A dict that maps board names to list of model names.
    """

  @abc.abstractmethod
  def _GeneratePayloads(self, board: str, models: Collection[str],
                        skip_model_check: bool = False) -> Optional[_Payload]:
    """Generates payloads.

    Args:
      board: Board name.
      models: Model names.
      skip_model_check: See Update().

    Returns:
      A generated payload instance.
      This will be None if no payloads are generated.
    """

  @abc.abstractmethod
  def _GetDeletedFiles(self, setting: config_data_module.CLSetting,
                       repo: git_util.MemoryRepo,
                       payloads: _Payload) -> Sequence[str]:
    """Returns name of files that need to be deleted.

    Compare the generated payloads with the existing payload files in the
    repository, and returns the nonexistent payloads files to be deleted.

    Args:
      setting: The repository settings.
      repo: The repository.
      board: The board name.
      payloads: The generated payloads.

    Returns:
      A list of file names indicating files to be deleted.
    """

  @abc.abstractmethod
  def _GetCLSetting(self, board: str) -> config_data_module.CLSetting:
    """Returns repository settings."""

  @abc.abstractmethod
  def _GetCLMessage(self, board: str, models: Collection[str],
                    payload: _Payload, hwid_commit: str,
                    hwid_prev_commit: str) -> str:
    """Returns the CL message."""

  @abc.abstractmethod
  def _PostUpdate(self, board: str, models: Collection[str], change_id: str,
                  payload: _Payload):
    """Runs additional operations after the CL is created.

    Override this function to run additional operations after the CL is created,
    such as updating datastore.

    Args:
      board: Board name.
      models: Model names.
      change_id: The CL change ID.
      payload: The payloads generated by _GeneratePayloads().
    """

  def _GetBoardModelsMapping(
      self, models: Collection[str],
      live_hwid_repo: hwid_repo.HWIDRepo) -> Mapping[str, list]:
    """Get a dict that maps board names to given model names.

    Query board names from DB metadata in the HWID repo, and returns a
    dictionary that associates the queried board name to the
    corresponding given models.

    Args:
      models: A list of model names to query.
      live_hwid_repo: See Update().

    Returns:
      A dict mapping board names to given model names.
    """
    board_models = collections.defaultdict(list)
    for model_name in models:
      try:
        db_metadata = live_hwid_repo.GetHWIDDBMetadataByName(model_name)
      except (KeyError, ValueError, RuntimeError) as ex:
        self._logger.error('Cannot get board data for %r: %r', model_name, ex)
        continue
      board_models[db_metadata.board_name].append(model_name)
    return board_models

  def Update(self, dryrun: bool, limit_models: Collection[str],
             force_update: bool, live_hwid_repo: hwid_repo.HWIDRepo,
             skip_model_check: bool = False) -> Mapping[str, UpdatedResult]:
    """Updates payload with the HWID DB.

    Args:
      dryrun: Do everything except actually upload the CL.
      limit_models: A set of models requiring payload generation, empty if
        unlimited.
      force_update: Generate payload change CLs without checking payload hash in
        advance.
      live_hwid_repo: A HWIDRepo instance being processed.
      skip_model_check: True if force use of limit_models without any model
        support check.

    Returns:
      A dict mapping board names to its updated results.
    """
    self._logger.info('Start syncing')

    hwid_live_commit = live_hwid_repo.hwid_db_commit_id
    if not self._cl_upload_manager.ShouldGenerateContent(
        hwid_live_commit, force_update):
      return {}
    self._logger.info('Sync with HWID commit %s', hwid_live_commit)
    hwid_prev_commit = self._cl_upload_manager.GetLatestHWIDMainCommit()

    self._RefreshCredential()
    assert self._auth_cookie is not None

    if skip_model_check:
      board_models = self._GetBoardModelsMapping(limit_models, live_hwid_repo)
    else:
      board_models = self._GetSupportedModels(limit_models, live_hwid_repo)

    result = {}
    author = self._author
    for board, models in board_models.items():
      payloads = self._GeneratePayloads(board, models, skip_model_check)
      if payloads is not None and self._cl_upload_manager.ShouldCreateCL(
          payloads.hash_value, board=board, force_create=force_update):
        setting = self._GetCLSetting(board)
        git_url = f'{setting.repo_host}/{setting.project}'
        branch = setting.branch or git_util.GetCurrentBranch(
            setting.review_host, setting.project, self._auth_cookie)
        git_files = [(os.path.join(
            setting.prefix, filepath), git_util.NORMAL_FILE_MODE, filecontent)
                     for filepath, filecontent in payloads.contents.items()]
        commit_msg = self._GetCLMessage(board, models, payloads,
                                        hwid_live_commit, hwid_prev_commit)
        try:
          repo = git_util.MemoryRepo(auth_cookie=self._auth_cookie)
          # only fetches last commit
          repo.shallow_clone(git_url, branch=branch)
          files_to_delete = self._GetDeletedFiles(setting, repo, payloads)
          change_id, unused_cl_number = self._cl_upload_manager.CreateCL(
              dryrun,
              git_url,
              self._auth_cookie,
              branch,
              git_files,
              author,
              author,
              commit_msg,
              self._config_data.is_prod_env(),
              repo=repo,
              topic=setting.topic,
              auto_submit=True,
              hashtags=setting.hashtags,
              files_to_delete=files_to_delete,
          )
          self._PostUpdate(board, models, change_id, payloads)
          result[board] = UpdatedResult(payloads.hash_value, change_id)
        except git_util.GitUtilNoModificationException:
          self._logger.debug('No modification is made, skipped')
        except git_util.GitUtilException as ex:
          self._logger.error('CL is not created: %r', str(ex))
          raise PayloadGenerationException('CL is not created') from ex

    self._cl_upload_manager.SetLatestHWIDMainCommit(hwid_live_commit)
    self._logger.info('Sync successfully to %s.', hwid_live_commit)
    return result

  def AbandonCLs(self, dryrun: bool, change_ids: Mapping[str, str]):
    """Abandons CLs with given change IDs."""
    assert self._auth_cookie is not None
    for board, change_id in change_ids.items():
      setting = self._GetCLSetting(board)
      try:
        self._cl_upload_manager.AbandonCL(dryrun, setting.review_host,
                                          self._auth_cookie, change_id)
      except git_util.GitUtilException as ex:
        self._logger.error('Cannot abandon CL for %r: %r', change_id, str(ex))


class _BaseFeatureEnablementPayloadManager(PayloadManager):
  """Collects common logic shared across feature-enablement payload mngrs."""

  def _GetSupportedModels(
      self, limit_models: Collection[str],
      live_hwid_repo: hwid_repo.HWIDRepo) -> Mapping[str, Collection[str]]:
    """See base class."""
    models = (
        limit_models
        if limit_models else set(live_hwid_repo.hwid_db_metadata_of_name))
    return self._GetBoardModelsMapping(models, live_hwid_repo)

  @abc.abstractmethod
  def _GetCLMessageSubject(self) -> str:
    """Gets the subject of the CL message."""

  def _GetCLMessage(self, board: str, models: Collection[str],
                    payload: _Payload, hwid_commit: str,
                    hwid_prev_commit: Optional[str]) -> str:
    """See base class."""

    generated_models = (
        payload.metadata['models'] if 'models' in payload.metadata else models)
    feature_matcher_paths = [
        f'v3/{model.upper()}.feature_matcher.textproto'
        for model in sorted(generated_models)
    ]
    if hwid_prev_commit is None:
      feature_matcher_file_objects = [
          f'{hwid_commit[:7]}:{path}' for path in feature_matcher_paths
      ]
      verification_command = (
          'git show \\\n' +
          textwrap.indent(' \\\n'.join(feature_matcher_file_objects), '  '))
    else:
      verification_command = (
          f'git diff {hwid_prev_commit[:7]}..{hwid_commit[:7]} -- \\\n' +
          textwrap.indent(' \\\n'.join(feature_matcher_paths), '  '))
    return textwrap.dedent(f"""\
        {self._GetCLMessageSubject()}

        From chromeos/chromeos-hwid: {hwid_commit}

        This CL is driven by the following HWID repository update:
    """) + textwrap.indent(verification_command, '  ')

  def _PostUpdate(self, board: str, models: Collection[str], change_id: str,
                  payload: _Payload):
    self._cl_upload_manager.SetLatestPayloadHash(payload.hash_value,
                                                 board=board)


class HWIDSelectionPayloadManager(_BaseFeatureEnablementPayloadManager):
  """A class managing payloads for HWID selection generated from HWID DB."""

  def _GeneratePayloads(self, board: str, models: Collection[str],
                        skip_model_check: bool = False) -> Optional[_Payload]:
    """See base class."""
    payload_builder = feature_matching.LegacyPayloadBuilder()
    generated_models = []
    for model in sorted(models):
      try:
        hwid_action = self._hwid_action_manager.GetHWIDAction(model)
        feature_matcher = hwid_action.GetFeatureMatcher()
        selection = feature_matcher.GenerateLegacyPayload()
        if selection is None:
          continue
        generated_models.append(model)
        payload_builder.AppendDeviceSelection(selection)
        payload_builder.ExtendDeviceSelectionSamples(
            feature_matcher.GenerateLegacyTestData())
      except (KeyError, ValueError, RuntimeError) as ex:
        self._logger.error('Cannot get model data: %r', ex)
        continue
    payload_msg = payload_builder.BuildDeviceSelection()
    if payload_msg is None:
      return None
    payloads = {
        'device_selection.textproto':
            payload_msg,
        'device_selection_sample.textproto':
            payload_builder.BuildDeviceSelectionSample(),
    }
    return _Payload(payloads, _JSONHash(payloads), {'models': generated_models})  # type: ignore #TODO(b/338318729) Fixit! # pylint: disable=line-too-long

  def _GetDeletedFiles(self, setting: config_data_module.CLSetting,
                       repo: git_util.MemoryRepo,
                       payloads: _Payload) -> Sequence[str]:
    """See base class."""
    # There are no files to be deleted for this manager.
    return []

  def _GetCLSetting(self, board: str) -> config_data_module.CLSetting:
    """See base class."""
    return config_data_module.CreateHWIDSelectionPayloadSettings(board)

  def _GetCLMessageSubject(self) -> str:
    """See base class."""
    return 'feature-management-bsp: update payload from hwid'


class RMADFeatureEnabledDevicesPayloadManager(
    _BaseFeatureEnablementPayloadManager):
  """A helper class that generates feature_enabled_devices proto for RMAD."""

  _PAYLOAD_FILE_NAME = 'devices.textproto'

  def _GeneratePayloads(self, board: str, models: Collection[str],
                        skip_model_check: bool = False) -> Optional[_Payload]:
    """See base class."""
    payloads = {}
    generated_models = []
    for model in models:
      try:
        hwid_action = self._hwid_action_manager.GetHWIDAction(model)
        feature_matcher = hwid_action.GetFeatureMatcher()
        file_contents = (
            feature_matcher.GenerateRMADFeatureEnabledDevicesPayload())
        if file_contents is None:
          continue
        generated_models.append(model)
        payloads[f'{model.lower()}/{self._PAYLOAD_FILE_NAME}'] = file_contents
      except (KeyError, ValueError, RuntimeError) as ex:
        self._logger.error('Cannot get model data: %r', ex)
        continue
    if not payloads:
      return None
    return _Payload(payloads, _JSONHash(payloads), {
        'models': generated_models
    })

  def _GetDeletedFiles(self, setting: config_data_module.CLSetting,
                       repo: git_util.MemoryRepo,
                       payloads: _Payload) -> Sequence[str]:
    """See base class."""
    if not repo.check_path_existence(setting.prefix):
      return []

    # Search the repository for existing files, if any is not in the `payloads`,
    # remove them.
    delete_files = []
    for dir_name, unused_mode, unused_data in repo.list_files(setting.prefix):
      payload_path_after_prefix = f'{dir_name}/{self._PAYLOAD_FILE_NAME}'
      payload_path = f'{setting.prefix}/{payload_path_after_prefix}'
      if not repo.check_path_existence(payload_path):
        continue

      if payload_path_after_prefix not in payloads.contents:
        delete_files.append(payload_path)

    return delete_files

  def _GetCLSetting(self, board: str) -> config_data_module.CLSetting:
    """See base class."""
    return config_data_module.CreateRMADFeatureEnabledDevicesPayloadSettings(
        board)

  def _GetCLMessageSubject(self) -> str:
    """See base class."""
    return 'rmad: Update feature allowlist from HWID.'


class VerificationPayloadManager(PayloadManager):
  """A class managing payloads for AVL verification generated from HWID DB."""

  def __init__(
      self,
      cl_upload_manager: cl_upload_config.VerificationPayloadCLUploadManager,
      hwid_action_manager: hwid_action_manager_module.HWIDActionManager,
      config_data: config_data_module.Config,
      decoder_data_manager: decoder_data_module.DecoderDataManager,
      vpg_targets_data_manager: vpg_targets_data.VPGTargetsDataManager):

    super().__init__(cl_upload_manager, hwid_action_manager, config_data)
    self._decoder_data_manager = decoder_data_manager
    self._vpg_targets_data_manager = vpg_targets_data_manager
    self._vpg_targets: Optional[Mapping[
        str, vpg_config_module.VerificationPayloadGeneratorConfig]] = None

  def _GetSupportedModels(
      self, limit_models: Collection[str],
      live_hwid_repo: hwid_repo.HWIDRepo) -> Mapping[str, Collection[str]]:
    """See base class."""
    assert self._vpg_targets is not None
    models = set(self._vpg_targets)
    if limit_models:
      models &= set(limit_models)
    return self._GetBoardModelsMapping(models, live_hwid_repo)

  def _GeneratePayloads(self, board: str, models: Collection[str],
                        skip_model_check: bool = False) -> Optional[_Payload]:
    """See base class."""
    assert self._vpg_targets is not None
    key = next(iter(self._config_data.vpg_keys), None)
    if key is None and any(
        vpg_target.encrypted for vpg_target in self._vpg_targets.values()):
      self._logger.error('Missing encrpytion keys')
      return None
    db_list = []
    for model in models:
      try:
        hwid_action = self._hwid_action_manager.GetHWIDAction(model)
        db = hwid_action.GetDBV3()
      except (KeyError, ValueError, RuntimeError) as ex:
        self._logger.error('Cannot get model data: %r', ex)

      if skip_model_check:
        db_list.append(
            (db, vpg_config_module.VerificationPayloadGeneratorConfig.Create()))
      else:
        vpg_target = self._vpg_targets[model]
        db_list.append((db, vpg_target))

    result = vpg_module.GenerateVerificationPayload(db_list, key)
    return _Payload(result.generated_file_contents, result.payload_hash, {
        'primary_identifier': result.primary_identifiers
    })

  def _GetDeletedFiles(self, setting: config_data_module.CLSetting,
                       repo: git_util.MemoryRepo,
                       payloads: _Payload) -> Sequence[str]:
    """See base class."""
    file_pattern = re.compile(r'runtime_probe/\w+/[\w\.]+')
    generated_files = {
        filepath
        for filepath in payloads.contents
        if file_pattern.fullmatch(filepath)
    }

    if not repo.check_path_existence(f'{setting.prefix}runtime_probe'):
      return []

    # Search the repository for existing files.
    delete_files = []
    for model, mode, unused_data in repo.list_files(
        f'{setting.prefix}runtime_probe'):
      if mode != git_util.DIR_MODE:
        continue

      for file_name, file_mode, unused_data in repo.list_files(
          f'{setting.prefix}runtime_probe/{model}'):
        if file_mode != git_util.NORMAL_FILE_MODE:
          continue

        if file_name in (
            'probe_config.json', 'probe_config.json.enc', 'encoding_spec.txtpb'
        ) and f'runtime_probe/{model}/{file_name}' not in generated_files:
          # The existing file is not generated anymore. Delete it.
          delete_files.append(
              f'{setting.prefix}runtime_probe/{model}/{file_name}')

    return delete_files

  def _GetCLSetting(self, board: str) -> config_data_module.CLSetting:
    """See base class."""
    return config_data_module.CreateVerificationPayloadSettings(board)

  def _GetCLMessage(self, board: str, models: Collection[str],
                    payload: _Payload, hwid_commit: str,
                    hwid_prev_commit: str) -> str:
    """See base class."""
    return textwrap.dedent(f"""\
        verification payload: update payload from hwid

        From chromeos/chromeos-hwid: {hwid_commit}
    """)

  def _PostUpdate(self, board: str, models: Collection[str], change_id: str,
                  payload: _Payload):
    """See base class."""
    self._cl_upload_manager.SetLatestPayloadHash(payload.hash_value,
                                                 board=board)
    if 'primary_identifier' in payload.metadata:
      self._decoder_data_manager.UpdatePrimaryIdentifiers(
          payload.metadata['primary_identifier'])

  def Update(self, dryrun: bool, limit_models: Collection[str],
             force_update: bool, live_hwid_repo: hwid_repo.HWIDRepo,
             skip_model_check: bool = False) -> Mapping[str, UpdatedResult]:
    """See base class."""
    self._vpg_targets = self._vpg_targets_data_manager.GetVpgTargets()
    return super().Update(dryrun, limit_models, force_update, live_hwid_repo,
                          skip_model_check)
