# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""Classes defining configs for the verification payload generator."""

from __future__ import annotations

from typing import List, Mapping, NamedTuple, Optional


class VerificationPayloadGeneratorConfig(NamedTuple):
  """A class to describe configs for the verification payload generator.

  Attributes:
    ignore_error: The list of component categories which means the error
        messages generated by their generator will be ignored.
    waived_comp_categories: The list of component categories which means their
        verification payload will not be generated.
    encrypted: The output payload should be encrypted.
  """

  ignore_error: List[str]
  waived_comp_categories: List[str]
  encrypted: bool

  @classmethod
  def Create(
      cls, ignore_error: Optional[List[str]] = None,
      waived_comp_categories: Optional[List[str]] = None,
      encrypted: Optional[bool] = False) -> VerificationPayloadGeneratorConfig:
    if ignore_error is None:
      ignore_error = []
    if waived_comp_categories is None:
      waived_comp_categories = []

    return cls(ignore_error=ignore_error,
               waived_comp_categories=waived_comp_categories,
               encrypted=encrypted)  # type: ignore #TODO(b/338318729) Fixit!

  @classmethod
  def BatchCreate(
      cls, config: Mapping[str, dict]
  ) -> Mapping[str, VerificationPayloadGeneratorConfig]:
    """Create batch configs from a dictionary.

    Args:
      config: A dictionary where key is model name and value is config
    Returns:
      A dictionary where key is model name and value is a verification payload
        generator config instance.
    """
    return {k: cls.Create(**v)
            for k, v in config.items()}
