# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
"""Classes defining configs for the verification payload generator."""

from __future__ import annotations

from typing import List, Mapping, NamedTuple, Optional


class VerificationPayloadGeneratorConfig(NamedTuple):
  """A class to describe configs for the verification payload generator.

  Attributes:
    ignore_error: The list of component categories which means the error
        messages generated by their generator will be ignored.
    waived_comp_categories: The list of component categories which means their
        verification payload will not be generated.
    encoding_spec_waived_categories: The list of component categories that will
        only be waived in the encoding specs but not the verification payloads.
    encrypted: The output payload should be encrypted.
  """

  ignore_error: List[str]
  waived_comp_categories: List[str]
  encoding_spec_waived_categories: List[str]
  encrypted: bool

  @classmethod
  def Create(
      cls, ignore_error: Optional[List[str]] = None,
      waived_comp_categories: Optional[List[str]] = None,
      encoding_spec_waived_categories: Optional[List[str]] = None,
      encrypted: Optional[bool] = False) -> VerificationPayloadGeneratorConfig:
    if ignore_error is None:
      ignore_error = []
    if waived_comp_categories is None:
      waived_comp_categories = []
    if encoding_spec_waived_categories is None:
      encoding_spec_waived_categories = []

    return cls(ignore_error=ignore_error,
               waived_comp_categories=waived_comp_categories,
               encoding_spec_waived_categories=encoding_spec_waived_categories,
               # yapf: disable
               encrypted=encrypted)  # type: ignore #TODO(b/338318729) Fixit! # pylint: disable=line-too-long
    # yapf: enable

  @classmethod
  def BatchCreate(
      cls, models_vp_on: Mapping[str, Mapping[str, dict]]
  ) -> Mapping[str, VerificationPayloadGeneratorConfig]:
    """Create batch configs from a dictionary.

    Args:
      models_vp_on: A dictionary where keys are board names and values are
          dictionaries that map model names to the configs.
    Returns:
      A dictionary where keys are model names and values are verification
      payload generator config instances.
    """
    return {
        model: cls.Create(**config)
        for unused_boards, configs in models_vp_on.items()
        for model, config in configs.items()
    }
